// Generated by https://quicktype.io

import { Product } from "./products";

export interface ProductResponse {
    product:  Product;
    products: Product[];
}



export enum Category {
    Laptops = "Laptops",
}
